name: Sync to Seuchico
on:
  push:
    branches:
      - master

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to mirror
        run: |
          # Removendo qualquer mirror anterior para garantir a atualização
          git remote remove mirror || true
          
          # Usando o formato de autenticação direta via Header/Token
          git remote add mirror https://x-access-token:${{ secrets.SYNC_TOKEN }}@github.com/seuchicoprojetos-sys/seuchicobotequim-cardapio.git
          
          git push --force --prune mirror refs/remotes/origin/master:refs/heads/master